// Generated by CoffeeScript 2.0.0-beta2
(function() {
  var Configuration, Daemon, dgram, fs, path, testCase;

  dgram = require("dgram");

  fs = require("fs");

  path = require("path");

  ({testCase} = require("nodeunit"));

  ({Configuration, Daemon} = require(".."));

  module.exports = testCase({
    setUp: function(proceed) {
      return proceed();
    },
    "start and stop": function(test) {
      var configuration, daemon;
      test.expect(2);
      configuration = new Configuration({
        MASQ_DNS_PORT: 0
      });
      daemon = new Daemon(configuration);
      daemon.start();
      return daemon.on("start", function() {
        test.ok(daemon.started);
        daemon.stop();
        return daemon.on("stop", function() {
          test.ok(!daemon.started);
          return test.done();
        });
      });
    },
    "start rolls back when it can't boot a server": function(test) {
      var server;
      test.expect(2);
      server = dgram.createSocket('udp4');
      return server.bind(0, function() {
        var configuration, daemon, port;
        port = server.address().port;
        configuration = new Configuration({
          MASQ_DNS_PORT: port
        });
        daemon = new Daemon(configuration);
        daemon.start();
        return daemon.on("error", function(err) {
          test.ok(err);
          test.ok(!daemon.started);
          server.close();
          return test.done();
        });
      });
    }
  });

}).call(this);
