// Generated by CoffeeScript 2.0.0-beta2
(function() {
  var Configuration, Logger, async, compilePattern, fs, getUserEnv, libraryPath, mkdirp, path, sourceScriptEnv;

  fs = require("fs");

  path = require("path");

  async = require("async");

  Logger = require("./logger");

  ({mkdirp} = require("./utils"));

  ({sourceScriptEnv} = require("./utils"));

  ({getUserEnv} = require("./utils"));

  module.exports = Configuration = (function() {
    class Configuration {
      static loadUserConfigurationEnvironment(callback) {
        return getUserEnv((err, env) => {
          var p;
          if (err) {
            return callback(err);
          } else {
            return fs.exists(p = this.userConfigurationPath, function(exists) {
              if (exists) {
                return sourceScriptEnv(p, env, callback);
              } else {
                return callback(null, env);
              }
            });
          }
        });
      }

      static getUserConfiguration(callback) {
        return this.loadUserConfigurationEnvironment(function(err, env) {
          if (err) {
            return callback(err);
          } else {
            return callback(null, new Configuration(env));
          }
        });
      }

      constructor(env = process.env) {
        this.logger = {};
        this.initialize(env);
      }

      initialize(env) {
        var base, base1, ref, ref1, ref2, ref3, ref4, ref5, ref6, ref7;
        this.bin = (ref = env.MASQ_BIN) != null ? ref : path.join(__dirname, "../bin/masq");
        this.dnsPort = (ref1 = env.MASQ_DNS_PORT) != null ? ref1 : 20560;
        this.domains = (ref2 = (ref3 = env.MASQ_DOMAINS) != null ? ref3 : env.MASQ_DOMAINS) != null ? ref2 : "dev";
        this.extDomains = (ref4 = env.MASQ_EXT_DOMAINS) != null ? ref4 : [];
        this.domains = (ref5 = typeof (base = this.domains).split === "function" ? base.split(",") : void 0) != null ? ref5 : this.domains;
        this.extDomains = (ref6 = typeof (base1 = this.extDomains).split === "function" ? base1.split(",") : void 0) != null ? ref6 : this.extDomains;
        this.allDomains = this.domains.concat(this.extDomains);
        this.allDomains.push(/\d+\.\d+\.\d+\.\d+\.xip\.io$/, /[0-9a-z]{1,7}\.xip\.io$/);
        this.supportRoot = libraryPath("Application Support", "Masq");
        this.logRoot = (ref7 = env.MASQ_LOG_ROOT) != null ? ref7 : libraryPath("Logs", "Masq");
        return this.dnsDomainPattern = compilePattern(this.domains);
      }

      toJSON() {
        var i, key, len, ref, result;
        result = {};
        ref = this.constructor.optionNames;
        for (i = 0, len = ref.length; i < len; i++) {
          key = ref[i];
          result[key] = this[key];
        }
        return result;
      }

      getLogger(name) {
        var base;
        return (base = this.loggers)[name] || (base[name] = new Logger(path.join(this.logRoot, name + ".log")));
      }

    };

    Configuration.userConfigurationPath = path.join(process.env.HOME, ".masqconfig");

    Configuration.optionNames = ["bin", "dnsPort", "domains", "extDomains", "logRoot"];

    return Configuration;

  })();

  libraryPath = function(...args) {
    return path.join(process.env.HOME, "Library", ...args);
  };

  compilePattern = function(domains) {
    return RegExp(`((^|\\.)(${domains.join("|")}))\\.?$`, "i");
  };

}).call(this);
